# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 09:04
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('GATE Preparation', 'GATE Preparation'), ('Thermodynamics', 'Thermodynamics'), ('Heat Transfer', 'Heat Transfer'), ('Fluid mechanics', 'Fluid mechanics'), ('Strength of Materials', 'Strength of Materials'), ('UPSC ESE ME', 'UPSC ESE ME'), ('Manufacturing Engineering', 'Manufacturing Engineering'), ('Engineering Design', 'Engineering Design'), ('Mechanics', 'Mechanics'), ('Analytical Reasoning', 'Analytical Reasoning'), ('Industrial engineering', 'Industrial engineering'), ('Automotive technology', 'Automotive technology'), ('Technology', 'Technology')], max_length=60)),
                ('author', models.CharField(default=0, max_length=60, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
    ]
