# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0004_auto_20170523_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
