# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 10:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default=0),
        ),
    ]
