# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 10:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Aapp', '0007_remove_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=0),
        ),
    ]
